name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on:
      - nix
      - ARM64
    steps:
      - name: AtomiCloud CI Environment
        uses: kirinnee/atomici-action@v2.3.1

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Remove GitHooks
        run: rm ./.git/hooks/*

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix-shell nix/shells.nix -A cd --run scripts/ci/release.sh
